# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 80
    onOpen: ignore
  - port: 443
    onOpen: ignore

tasks:
  - name: startup tasks
    command: |
      docker-compose up
